S := formula / number / coord / text

<formula> := <'='> call

col := #'[A-Z]+'
row := #'[0-9]+'
coord := col row

range := coord <':'> coord

number := #'[+-]?\d*\.?\d+'

text := #"[^=].*"

fn := #'[A-Za-z_]+'
<arg> := call | number | coord | range
<args> := <ws?> arg <ws?> [<',' ws?> args] <ws?>
argv := args
call := fn <'('> argv <')'>

ws := #'\s+'
